{{
	config(
		materialized='incremental',
		unique_key='POLICYID',
		schema= 'DIM'
	)
}}	
	
	
SELECT  PLM.POLID AS POLICYID, 
        INP.UNITPSU AS BUSINESSUNIT, 
        INP.ACCTGYR AS ACCYEAR,
        PLM.ENTST AS ENTRYSTATUS, PLM.INCPDT AS INCEPTIONDATE, 
        PLM.PMAMT AS PREMIUMAMOUNT, 
        PLM.PMCCY AS PREMIUMCURR, 
        PLM.POLTY AS POLICYTYPE, 
        PLM.USRPSU AS USERNAME, 
        PLM.UWR AS UNDERWRITER, 
        COALESCE(PLKF.ORIGPOLID,PLKT.ORIGPOLID,PLM.POLID) AS MASTERPOLICYID, -- New code here
        NULL AS COVERPOLICYID , 
        SPLIT(LISTAGG(DISTINCT PLY.CD,','),',') AS POLICYANALYSISCODE, 
        POLTY AS POLICYANALYSISTYPE, 
        {{surrogate_key('POLICYID', 'POLTY')}}  AS POLICYIDSK

FROM "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLMAIN" PLM
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."INPOL" INP
ON INP.POLID = PLM.POLID
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLLNK" PLKF 
ON PLKF.FRPOLID = PLM.POLID 
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLLNK" PLKT 
ON PLKT.TOPOLID = PLM.POLID 
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLANLYCD" PLY
ON PLY.POLID = PLM.POLID

GROUP BY PLM.POLID, INP.UNITPSU, INP.ACCTGYR, PLM.ENTST, PLM.INCPDT, PLM.PMAMT, PLM.PMCCY, PLM.POLTY, PLM.USRPSU, PLM.UWR, PLKF.ORIGPOLID, PLKT.ORIGPOLID