{{
	config(
		materialized='incremental',
		unique_key='POLICYID',
		schema= 'DIM'
	)
}}
SELECT DISTINCT PLM.POLID AS POLICYID, INP.UNITPSU AS BUSINESSUNIT, INP.ACCTGYR AS ACCYEAR  ,PLM.ENTST AS ENTRYSTATUS, PLM.INCPDT AS INCEPTIONDATE, PLM.PMAMT AS PREMIUMAMOUNT, PLM.PMCCY AS PREMIUMCURR, PLM.POLTY AS POLICYTYPE, PLM.USRPSU AS USERNAME, PLM.UWR AS UNDERWRITER, NULL AS MASTERPOLICYID, NULL AS COVERPOLICYID , PLY.CD AS POLICYANALYSISCODE, POLTY AS POLICYANALYSISTYPE, {{surrogate_key('POLICYID', 'POLTY')}} AS POLICYIDSK
FROM "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLMAIN" PLM
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."INPOL" INP
ON INP.POLID = PLM.POLID
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLANLYCD" PLY
ON PLY.POLID = PLM.POLID
	
	
	
