{{
	config(
		materialized='incremental',
		unique_key='TRANSACTIONID',
		schema='FACT'
	)
}}
SELECT DISTINCT USM.TRNID AS TRANSACTIONID, USM.POLID AS POLICYID, BKRCD AS BROKERID, RSKCD AS RISKID, CAC AS TRANSTYPEID, USM.ACCPRD AS ACCPERIOD, ACCYR AS ACCYEAR, LPSODT AS TRANSACTIONDATE, ACTPYMTDT AS ACTUALPAYMENTDATE, CASE WHEN CAC IN (4,5) THEN NETAMT ELSE NULL END AS CLAIMAMOUNT, CASE WHEN CAC IN (1,2,3) THEN NETAMT ELSE NULL END AS PREMIUMAMOUNT, USM.TRNCGY AS TRANCATEGORY, MRN AS MARKETREFNO, TRNVERNO AS TRANVERSIONNO, USM.UMR AS UNIQUEMARKETREF, UCR AS UNIQUECLAIMREF, ENTTY AS ENTRYTYPE, BUSCGY AS BUSINESSCATEGORY, SCC AS SETTLEMENTCURR,  OCC AS ORIGINALCURR, {{surrogate_key('BkrCd', 'BkrRef', 'USM.BkrPSU')}} AS BROKERIDSK, {{surrogate_key('CAC', 'BusCgyTy')}} AS TRANSTYPEIDSK, {{surrogate_key('USM.POLID', 'POL.POLTY')}} AS POLICYIDSK
FROM "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."USMMAIN" USM
LEFT JOIN "PC_FIVETRAN_DB"."SUBSCRIBE_DBO"."POLMAIN" POL
ON POL.POLID = USM.POLID
